# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>

development:
  <<: *default
  database: policy_manager_development
  url: <%= ENV['DEVELOP_DATABASE_URL'] %>

test:
  <<: *default
  database: policy_manager_test
  url: <%= ENV['TEST_DATABASE_URL'] %>

production:
  <<: *default
  database: policy_manager_production
  username: policy_manager
  url: <%= ENV['PROD_DATABASE_URL'] %>
